codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 2  # Wait for both Node 18.x and 20.x matrix builds

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
        if_ci_failed: error
    patch:
      default:
        target: auto
        threshold: 1%

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "backend/dist/**"
  - "backend/coverage/**"
  - "backend/node_modules/**"
  - "backend/src/__tests__/**"
  - "frontend/dist/**"
  - "frontend/node_modules/**"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"

flags:
  backend:
    paths:
      - backend/src/
    carryforward: true
