import axios from 'axios';
import { DetectedError } from '../types/errors';

interface GitHubConfig {
  token: string;
  owner: string;
  repo: string;
}

interface GitHubIssue {
  number: number;
  html_url: string;
  title: string;
}

export class GitHubIssueCreator {
  private config: GitHubConfig;
  private baseUrl: string;

  constructor(config: GitHubConfig) {
    this.config = config;
    this.baseUrl = `https://api.github.com/repos/${config.owner}/${config.repo}`;
  }

  async createIssue(error: DetectedError, railwayProjectId: string): Promise<GitHubIssue | null> {
    try {
      const title = this.generateIssueTitle(error);
      const body = this.generateIssueBody(error, railwayProjectId);
      const labels = this.generateLabels(error);

      const response = await axios.post(
        `${this.baseUrl}/issues`,
        {
          title,
          body,
          labels,
        },
        {
          headers: {
            Authorization: `token ${this.config.token}`,
            Accept: 'application/vnd.github.v3+json',
          },
        }
      );

      return {
        number: response.data.number,
        html_url: response.data.html_url,
        title: response.data.title,
      };
    } catch (error) {
      console.error('Failed to create GitHub issue:', error);
      return null;
    }
  }

  async addCommentToIssue(issueNumber: number, comment: string): Promise<boolean> {
    try {
      await axios.post(
        `${this.baseUrl}/issues/${issueNumber}/comments`,
        { body: comment },
        {
          headers: {
            Authorization: `token ${this.config.token}`,
            Accept: 'application/vnd.github.v3+json',
          },
        }
      );
      return true;
    } catch (error) {
      console.error('Failed to add comment to issue:', error);
      return false;
    }
  }

  async addLabels(issueNumber: number, labels: string[]): Promise<boolean> {
    try {
      await axios.post(
        `${this.baseUrl}/issues/${issueNumber}/labels`,
        { labels },
        {
          headers: {
            Authorization: `token ${this.config.token}`,
            Accept: 'application/vnd.github.v3+json',
          },
        }
      );
      return true;
    } catch (error) {
      console.error('Failed to add labels:', error);
      return false;
    }
  }

  async removeLabel(issueNumber: number, label: string): Promise<boolean> {
    try {
      await axios.delete(`${this.baseUrl}/issues/${issueNumber}/labels/${label}`, {
        headers: {
          Authorization: `token ${this.config.token}`,
          Accept: 'application/vnd.github.v3+json',
        },
      });
      return true;
    } catch (error) {
      console.error('Failed to remove label:', error);
      return false;
    }
  }

  private generateIssueTitle(error: DetectedError): string {
    const emoji = this.getSeverityEmoji(error.severity);
    const service = error.serviceName.charAt(0).toUpperCase() + error.serviceName.slice(1);
    const message = error.errorMessage.substring(0, 60);

    return `${emoji} [${service}] ${message}${error.errorMessage.length > 60 ? '...' : ''}`;
  }

  private generateIssueBody(error: DetectedError, railwayProjectId: string): string {
    const railwayLogsUrl = `https://railway.app/project/${railwayProjectId}`;
    const railwayServiceUrl = `${railwayLogsUrl}/${error.serviceName}`;

    return `## 🤖 Automated Error Detection

An error was detected in the **${error.serviceName}** service logs.

### Error Details
- **Service**: ${error.serviceName}
- **Category**: ${error.category}
- **Severity**: ${error.severity}
- **First Seen**: ${error.firstSeen.toISOString()}
- **Last Seen**: ${error.lastSeen.toISOString()}
- **Occurrences**: ${error.occurrenceCount}
${error.deploymentId ? `- **Deployment**: ${error.deploymentId}` : ''}

### Error Message
\`\`\`
${error.errorMessage}
\`\`\`

### Error Logs
\`\`\`
${error.logs.join('\n')}
\`\`\`

### Railway Context
- [View Service](${railwayServiceUrl})
- [View Project](${railwayLogsUrl})
- Environment: production

---

@claude Please analyze these error logs and provide:
1. Root cause analysis
2. Severity assessment
3. Specific fix suggestions with code examples
4. Prevention recommendations

*Auto-generated by Intelligence Service*`;
  }

  private generateLabels(error: DetectedError): string[] {
    const labels = ['needs-claude-analysis', 'automated', 'railway-logs'];

    // Add service label
    labels.push(error.serviceName);

    // Add severity label
    labels.push(`severity:${error.severity}`);

    // Add category label
    labels.push(`category:${error.category}`);

    return labels;
  }

  private getSeverityEmoji(severity: string): string {
    switch (severity) {
      case 'critical':
        return '🚨';
      case 'high':
        return '⚠️';
      case 'medium':
        return '⚡';
      case 'low':
        return '📌';
      default:
        return '🔍';
    }
  }

  async createRecurrenceComment(
    issueNumber: number,
    occurrences: number,
    lastSeen: Date
  ): Promise<boolean> {
    const comment = `## ⚠️ Error Recurred

**New Occurrences**: ${occurrences}
**Last Seen**: ${lastSeen.toISOString()}

The issue persists. Please prioritize investigation.

*Updated by Intelligence Service*`;

    return this.addCommentToIssue(issueNumber, comment);
  }
}
